CREATE TABLE "AC_BAS_TIPOS_USUARIOS"
(
   "TIPO_USUARIO_ID"            BIGSERIAL NOT NULL
  ,"DESCRIPCION"                VARCHAR(32) NOT NULL
  ,"ACTIVO"                     BOOLEAN NOT NULL
  ,"FECHA_CREACION"             TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_CREACION"           VARCHAR(32) NOT NULL
  ,"FECHA_ACTUALIZACION"        TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_ACTUALIZACION"      VARCHAR(32) NOT NULL
  ,CONSTRAINT "PK_AC_BAS_TIPOS_USUARIOS" PRIMARY KEY ("TIPO_USUARIO_ID")
  );

CREATE TABLE "AC_BAS_USUARIOS"
(
   "USUARIO_ID"                 BIGSERIAL NOT NULL
  ,"USUARIO"                    VARCHAR(32) NOT NULL
  ,"CLAVE_ACCESO"               VARCHAR(256) NOT NULL
  ,"CORREO_ELECTRONICO"         VARCHAR(320) NOT NULL
  ,"TIPO_USUARIO_ID"            BIGINT NOT NULL
  ,"ACTIVO"                     BOOLEAN NOT NULL
  ,"FECHA_CREACION"             TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_CREACION"           VARCHAR(32) NOT NULL
  ,"FECHA_ACTUALIZACION"        TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_ACTUALIZACION"      VARCHAR(32) NOT NULL
  ,CONSTRAINT "PK_AC_BAS_USUARIOS" PRIMARY KEY ("USUARIO_ID")
  ,CONSTRAINT "FK_AC_BAS_USUARIOS_TIPO_USUARIO_ID" FOREIGN KEY ("TIPO_USUARIO_ID") REFERENCES "AC_BAS_TIPOS_USUARIOS" ("TIPO_USUARIO_ID")
  );

CREATE TABLE "AC_APP_ROLES"
(
   "ROL_ID"                     BIGSERIAL NOT NULL
  ,"DESCRIPCION"                VARCHAR(64) NOT NULL
  ,"ACTIVO"                     BOOLEAN NOT NULL
  ,"FECHA_CREACION"             TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_CREACION"           VARCHAR(32) NOT NULL
  ,"FECHA_ACTUALIZACION"        TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_ACTUALIZACION"      VARCHAR(32) NOT NULL
  ,CONSTRAINT "PK_AC_APP_ROLES" PRIMARY KEY ("ROL_ID")
);

CREATE TABLE "AC_APP_USUARIOS_POR_ROLES"
(
   "USUARIO_ID"                 BIGINT NOT NULL
  ,"ROL_ID"                     BIGINT NOT NULL
  ,"ACTIVO"                     BOOLEAN NOT NULL
  ,"FECHA_CREACION"             TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_CREACION"           VARCHAR(32) NOT NULL
  ,"FECHA_ACTUALIZACION"        TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_ACTUALIZACION"      VARCHAR(32) NOT NULL
  ,CONSTRAINT "PK_AC_APP_USUARIOS_POR_ROLES" PRIMARY KEY ("USUARIO_ID","ROL_ID")
  ,CONSTRAINT "FK_AC_APP_USUARIOS_POR_ROLES_USUARIO_ID" FOREIGN KEY ("USUARIO_ID") REFERENCES "AC_BAS_USUARIOS" ("USUARIO_ID")
  ,CONSTRAINT "FK_AC_APP_USUARIOS_POR_ROLES_ROL_ID" FOREIGN KEY ("ROL_ID") REFERENCES "AC_APP_ROLES" ("ROL_ID")
);

CREATE TABLE "AC_APP_FUNCIONARIOS"
(
   "FUNCIONARIO_ID"             BIGSERIAL NOT NULL
  ,"USUARIO_ID"                 BIGINT NOT NULL
  ,"NUMERO_IDENTIFICACION"      VARCHAR(128) NOT NULL
  ,"NOMBRE"                     VARCHAR(64) NOT NULL
  ,"APELLIDO"                   VARCHAR(64) NOT NULL
  ,"TELEFONO"                   VARCHAR(11) NOT NULL
  ,"DIRECCION"                  VARCHAR(256) NOT NULL
  ,"ACTIVO"                     BOOLEAN NOT NULL
  ,"FECHA_CREACION"             TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_CREACION"           VARCHAR(32) NOT NULL
  ,"FECHA_ACTUALIZACION"        TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_ACTUALIZACION"      VARCHAR(32) NOT NULL
  ,CONSTRAINT "PK_AC_APP_FUNCIONARIOS" PRIMARY KEY ("FUNCIONARIO_ID")
  ,CONSTRAINT "FK_AC_APP_FUNCIONARIOS_USUARIO_ID" FOREIGN KEY ("USUARIO_ID") REFERENCES "AC_BAS_USUARIOS" ("USUARIO_ID")
  );

CREATE TABLE "AC_APP_CLIENTES"
(
   "CLIENTE_ID"                 BIGSERIAL NOT NULL
  ,"NUMERO_IDENTIFICACION"      VARCHAR(128) NOT NULL
  ,"NOMBRE"                     VARCHAR(64) NOT NULL
  ,"APELLIDO"                   VARCHAR(64) NOT NULL
  ,"TELEFONO"                   VARCHAR(11) NOT NULL
  ,"DIRECCION"                  VARCHAR(256) NOT NULL
  ,"ACTIVO"                     BOOLEAN NOT NULL
  ,"FECHA_CREACION"             TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_CREACION"           VARCHAR(32) NOT NULL
  ,"FECHA_ACTUALIZACION"        TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_ACTUALIZACION"      VARCHAR(32) NOT NULL
  ,CONSTRAINT "PK_AC_APP_CLIENTES" PRIMARY KEY ("CLIENTE_ID")
  );

CREATE TABLE "AC_APP_MARCAS"
(
   "MARCA_ID"                   BIGSERIAL NOT NULL
  ,"DESCRIPCION"                VARCHAR(64) NOT NULL
  ,"ACTIVO"                     BOOLEAN NOT NULL
  ,"FECHA_CREACION"             TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_CREACION"           VARCHAR(32) NOT NULL
  ,"FECHA_ACTUALIZACION"        TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_ACTUALIZACION"      VARCHAR(32) NOT NULL
  ,CONSTRAINT "PK_AC_APP_MARCAS" PRIMARY KEY ("MARCA_ID")
);

CREATE TABLE "AC_APP_PROVEEDORES"
(
   "PROVEEDOR_ID"               BIGSERIAL NOT NULL
  ,"DESCRIPCION"                VARCHAR(64) NOT NULL
  ,"TELEFONO"                   VARCHAR(32) NOT NULL
  ,"CORREO ELECTRONICO"         VARCHAR(320) NOT NULL
  ,"ACTIVO"                     BOOLEAN NOT NULL
  ,"FECHA_CREACION"             TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_CREACION"           VARCHAR(32) NOT NULL
  ,"FECHA_ACTUALIZACION"        TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_ACTUALIZACION"      VARCHAR(32) NOT NULL
  ,CONSTRAINT "PK_AC_APP_PROVEEDORES" PRIMARY KEY ("PROVEEDOR_ID")
);

CREATE TABLE "AC_APP_CATEGORIAS"
(
   "CATEGORIA_ID"               BIGSERIAL NOT NULL
  ,"DESCRIPCION"                VARCHAR(64) NOT NULL
  ,"ACTIVO"                     BOOLEAN NOT NULL
  ,"FECHA_CREACION"             TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_CREACION"           VARCHAR(32) NOT NULL
  ,"FECHA_ACTUALIZACION"        TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_ACTUALIZACION"      VARCHAR(32) NOT NULL
  ,CONSTRAINT "PK_AC_APP_CATEGORIAS" PRIMARY KEY ("CATEGORIA_ID")
);

CREATE TABLE "AC_APP_PRODUCTOS"
(
   "PRODUCTO_ID"                BIGSERIAL NOT NULL
  ,"MARCA_ID"                   BIGINT NOT NULL
  ,"PROVEEDOR_ID"               BIGINT NOT NULL
  ,"CATEGORIA_ID"               BIGINT NOT NULL
  ,"DESCRIPCION"                VARCHAR(64) NOT NULL
  ,"OBSERVACIONES"              VARCHAR(128) NOT NULL
  ,"VALOR"                      VARCHAR(128) NOT NULL
  ,"VALOR_IMPUESTO"             VARCHAR(128) NOT NULL
  ,"ACTIVO"                     BOOLEAN NOT NULL
  ,"FECHA_CREACION"             TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_CREACION"           VARCHAR(32) NOT NULL
  ,"FECHA_ACTUALIZACION"        TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_ACTUALIZACION"      VARCHAR(32) NOT NULL
  ,CONSTRAINT "PK_AC_APP_PRODUCTOS" PRIMARY KEY ("PRODUCTO_ID")
  ,CONSTRAINT "FK_AC_APP_PRODUCTOS_MARCA_ID" FOREIGN KEY ("MARCA_ID") REFERENCES "AC_APP_MARCAS" ("MARCA_ID")
  ,CONSTRAINT "FK_AC_APP_PRODUCTOS_PROVEEDOR_ID" FOREIGN KEY ("PROVEEDOR_ID") REFERENCES "AC_APP_PROVEEDORES" ("PROVEEDOR_ID")
  ,CONSTRAINT "FK_AC_APP_PRODUCTOS_CATEGORIA_ID" FOREIGN KEY ("CATEGORIA_ID") REFERENCES "AC_APP_CATEGORIAS" ("CATEGORIA_ID")
  );

CREATE TABLE "AC_APP_INVENTARIOS"
(
   "INVENTARIO_ID"              BIGSERIAL NOT NULL
  ,"PRODUCTO_ID"                BIGINT NOT NULL
  ,"ACTIVO"                     BOOLEAN NOT NULL
  ,"FECHA_CREACION"             TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_CREACION"           VARCHAR(32) NOT NULL
  ,"FECHA_ACTUALIZACION"        TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_ACTUALIZACION"      VARCHAR(32) NOT NULL
  ,CONSTRAINT "PK_AC_APP_INVENTARIOS" PRIMARY KEY ("INVENTARIO_ID")
  ,CONSTRAINT "FK_AC_APP_INVENTARIOS_PRODUCTO_ID" FOREIGN KEY ("PRODUCTO_ID") REFERENCES "AC_APP_PRODUCTOS" ("PRODUCTO_ID")
  );

CREATE TABLE "AC_APP_PROMOCIONES"
(
   "PROMOCION_ID"               BIGSERIAL NOT NULL
  ,"DESCRIPCION"                VARCHAR(64) NOT NULL
  ,"ACTIVO"                     BOOLEAN NOT NULL
  ,"FECHA_CREACION"             TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_CREACION"           VARCHAR(32) NOT NULL
  ,"FECHA_ACTUALIZACION"        TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_ACTUALIZACION"      VARCHAR(32) NOT NULL
  ,CONSTRAINT "PK_AC_APP_PROMOCIONES" PRIMARY KEY ("PROMOCION_ID")
);

CREATE TABLE "AC_APP_VENTAS"
(
   "VENTA_ID"                   BIGSERIAL NOT NULL
  ,"FUNCIONARIO_ID"             BIGINT NOT NULL
  ,"CLIENTE_ID"                 BIGINT NOT NULL
  ,"PROMOCION"                  VARCHAR(64) NOT NULL
  ,"DESCUENTO"                  VARCHAR(128) NOT NULL
  ,"ACTIVO"                     BOOLEAN NOT NULL
  ,"FECHA_CREACION"             TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_CREACION"           VARCHAR(32) NOT NULL
  ,"FECHA_ACTUALIZACION"        TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_ACTUALIZACION"      VARCHAR(32) NOT NULL
  ,CONSTRAINT "PK_AC_APP_VENTAS" PRIMARY KEY ("VENTA_ID")
  ,CONSTRAINT "FK_AC_APP_VENTAS_FUNCIONARIO_ID" FOREIGN KEY ("FUNCIONARIO_ID") REFERENCES "AC_APP_FUNCIONARIOS" ("FUNCIONARIO_ID")
  ,CONSTRAINT "FK_AC_APP_VENTAS_CLIENTE_ID" FOREIGN KEY ("CLIENTE_ID") REFERENCES "AC_APP_CLIENTES" ("CLIENTE_ID")
  );

CREATE TABLE "AC_APP_DEVOLUCIONES"
(
   "DEVOLUCION_ID"              BIGSERIAL NOT NULL
  ,"VENTA_ID"                   BIGINT NOT NULL
  ,"ACTIVO"                     BOOLEAN NOT NULL
  ,"FECHA_CREACION"             TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_CREACION"           VARCHAR(32) NOT NULL
  ,"FECHA_ACTUALIZACION"        TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_ACTUALIZACION"      VARCHAR(32) NOT NULL
  ,CONSTRAINT "PK_AC_APP_DEVOLUCIONES" PRIMARY KEY ("DEVOLUCION_ID")
  ,CONSTRAINT "FK_AC_APP_DEVOLUCIONES_VENTA_ID" FOREIGN KEY ("VENTA_ID") REFERENCES "AC_APP_VENTAS" ("VENTA_ID")
);

CREATE TABLE "AC_APP_DETALLE_VENTAS"
(
   "DETALLE_VENTA_ID"           BIGSERIAL NOT NULL
  ,"VENTA_ID"                   BIGINT NOT NULL
  ,"PRODUCTO_ID"                BIGINT NOT NULL
  ,"VALOR_UNITARIO_IMPUESTO"    VARCHAR(128) NOT NULL
  ,"CANTIDAD"                   VARCHAR(128) NOT NULL
  ,"VALOR_UNITARIO"             VARCHAR(128) NOT NULL
  ,"ACTIVO"                     BOOLEAN NOT NULL
  ,"FECHA_CREACION"             TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_CREACION"           VARCHAR(32) NOT NULL
  ,"FECHA_ACTUALIZACION"        TIMESTAMP WITHOUT TIME ZONE NOT NULL
  ,"USUARIO_ACTUALIZACION"      VARCHAR(32) NOT NULL
  ,CONSTRAINT "PK_AC_APP_DETALLE_VENTAS" PRIMARY KEY ("DETALLE_VENTA_ID")
  ,CONSTRAINT "FK_AC_APP_DETALLE_VENTAS_VENTA_ID" FOREIGN KEY ("VENTA_ID") REFERENCES "AC_APP_VENTAS" ("VENTA_ID")
  ,CONSTRAINT "FK_AC_APP_DETALLE_VENTAS_PRODUCTO_ID" FOREIGN KEY ("PRODUCTO_ID") REFERENCES "AC_APP_PRODUCTOS" ("PRODUCTO_ID")
  );